JeongHanO/SomeThink

client/src/components/Canvas/MindMap.js

노드 질량 0
노드 모양 원형으로
화살표 제거
기본 색상 부여
설정창 ON

✨ make basic node work

---

client/src/components/Canvas/MindMap.js
client/src/components/Canvas/NodeContextMenu.js

컨텍스트 메뉴에서 '노드 삭제' 클릭 시, 선택한 노드를 삭제하는 기능을 추가

✨ delete node features

---

client/src/components/Canvas/MindMap.js

🐛 fix issue of moving position after label modification

---

client/src/components/Canvas/MindMap.js
client/src/components/Canvas/NodeContextMenu.js

⚡️ improve AddNode and physics features

---

client/package-lock.json
client/src/App.js
client/src/components/Canvas/MindMap.js
client/src/components/LowToolBar/LowToolBar.js

💄modify toolbar

---

client/src/App.js
client/src/components/Canvas/Canvas.js
client/src/components/Canvas/MindMap.js
client/src/components/TopBar/TopBar.js

마우스 트레킹 동기화 문제 해결 및 topbar 버그 픽스

🐛 fix mouse move concurrency & topbar

---

client/src/components/Canvas/MindMap.js
client/src/components/LowToolBar/LowToolBar.js
server/package-lock.json
server/package.json

🐛fix navigation bar toggle

---

client/src/App.js
client/src/components/Canvas/UserMouseMove.js

홈화면 클릭 안되는 버그 개선 및 방번호 영어 및 숫자만 입력하게 수정, 마우스 트레킹 한글 세로로 보이던점 개선

💄fix homopage ui

---

client/src/App.js

세션 떠나서 홈화면으로 돌아가면 흰 배경으로 바뀌는 부분 수정

💄leaveSession background color fix

---

client/src/components/Canvas/MindMap.js

특정 상황들에서 유저 하이라이트가 지워지지 않고 남는 현상을 수정하였습니다.

🐛 Debug Highlight

---

client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/MindMap.js

북마크 기능을 단순 노드 모양 변경에서, 별도의 노드를 위에 달아주는 식으로 수정하였습니다. 이로 인한 각종 이벤트 관련 처리들과, 생성 삭제 로직 또한 추가하였습니다.

✨ BookMark Work

---

client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/MindMap.js

노드 라벨 수정시에도 undo, redo가 작동하도록 로직을 추가하였습니다.

✨ Add modify ctrl + z

---

client/public/index.html
client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/MindMap.js

기존의 로직을 없애고, 북마크 방식을 단순 색 변경으로 교체하였습니다.

✨ Change bookmark method

---

client/src/Constant.js
client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/MindMap.js
client/src/components/Canvas/UserMouseMove.js

빈번히 사용되며, 가독성을 해치는 변수들을 상수로 묶어 처리했습니다.

♻️ Refactor work

---

client/src/Constant.js
client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/MindMap.js

드래그 이벤트 발생 간격에 미세한 딜레이를 두어 서버 부하 개선

⚡️ Make delay on drag

---

client/package.json
client/src/components/Canvas/MindMap.js
client/src/components/TopBar/TopBar.js

클릭을 통해 방 코드를 클립보드에 복사할 수 있도록 하였습니다.

✨ Can copy code with click

---

client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/MindMap.js

엣지 생성, 삭제, 북마크 생성, 삭제시에 Undo, Redo가 동작하도록 하였습니다.

✨ Undo Redo Work

---

client/src/components/Canvas/MindMap.js
client/src/components/TopBar/TopBar.js

코드에 마우스 올릴 시 커서 변경,
Ctrl+Z 버그 수정

🐛 Some debug, UI work

---

client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/ImageSearch.js
client/src/components/Canvas/MindMap.js

1. 이미지 서치 버튼 마우스 호버링 시, 더 이상 백그라운드를 투시하여 보여주지 않습니다.
2.이미지 서치와 바로가기 두 모달창의 바깥을 클릭 할 시 모달창이 닫히도록 하였습니다.

💄 Improve UI/UX

---

client/src/Constant.js
client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/MindMap.js
client/src/components/TopBar/TopBar.js
client/src/components/openai/api.js

노드에게 색을 입히는 부분들을 삭제하고,
루트 노드 기준 각 분기의 노드들이 동일한 그룹을 가지도록 했습니다.

Node color work

---

client/src/Constant.js
client/src/components/Canvas/EventHandler.js
client/src/components/Canvas/MindMap.js

1. 마인드맵 입장 시 애니메이션을 적용하였습니다.
2. 상수 처리를 통해 코드 가독성을 높였습니다.
3. 기존에는 마인드맵을 참조 해주는 이벤트가 엄청 많이 발생했는데, 한 번만 적용되도록 변경하여 성능을 개선하였습니다.

MindMap enter animation, refactor work
